---
  version: '3.7'
  services:
    db-core:
      image: mysql:8.0.12
      volumes:
        - ../../db:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: "mamram"
      ports:
        - "7306:3306"

    app:
      build:
        context: ../../.
      environment:
        DB_HOST: "db-core"
        DB_PORT: "3306"
        DB_PASSWORD: "mamram"
      command: yarn test:int
      depends_on:
        - db-core
